site_name: Nchu-Security-wiki
markdown_extensions:
    - footnotes    #支持脚注
    - admonition   #支持注解
    - pymdownx.details
    - codehilite:
        guess_lang: false
    - toc:
        permalink: true
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format ''

extra_javascript:
  - custom/mathjax.js
  
theme: 
  name: material
  palette:
    scheme: default
    primary: white
  features:
    - navigation.tabs
    - header.autohide
  icon:
    repo: fontawesome/brands/github
  edit_uri: ""
  repo_url: https://github.com/xPessimist/Notes
nav:
#- Start:
#  - index.md    yml文件只支持单行注释
- Introduction:
  - index.md 
#  - Introduction/starttime.md
- 计算机基础知识:
  - 计算机基础知识/start.md
  - 计算机基础知识/c语言.md
  - 计算机基础知识/数据结构与算法.md
  - 计算机基础知识/计算机组成.md
  - 计算机基础知识/操作系统.md
  - 计算机基础知识/计算机网络.md
- 工具:
  - 工具/start.md
  - 工具/git手册.md
  - 工具/markdown.md
  - 工具/虚拟机.md
  - 工具/linux使用教程.md
  - 工具/wireshark.md
  - 工具/burpsuite.md
  - 工具/nmap.md
  - 工具/netcat.md
  - 工具/metasploit.md
  - 工具/cs.md
  
- Web安全:
  - web安全/基础知识.md
  - web安全/HTTP协议相关漏洞.md
  - web安全/sql注入.md
  - web安全/文件上传.md
  - web安全/文件包含.md
  - web安全/xss.md
  - web安全/csrf.md
  - web安全/浏览器安全.md
  - web安全/ssrf.md
  - web安全/xxe.md
  - web安全/代码、命令执行.md
  - web安全/反序列化漏洞.md
  - web安全/SSTI.md
  - web安全/条件竞争.md
  - web安全/其他漏洞.md
  - web安全/业务逻辑漏洞.md
  - web安全/web中间件漏洞.md
- 渗透测试:
  - 渗透测试/start.md
  - 渗透测试/信息收集.md
  - 渗透测试/漏洞探测和利用.md
  - 渗透测试/后渗透.md
  - 渗透测试/内网渗透.md
  - 渗透测试/域渗透.md
  - 渗透测试/痕迹清除.md
- Pwn:
  - pwn/start.md
  - pwn/pwn工具.md
  - pwn/动态链接.md
  - pwn/基本ROP.md
  - pwn/栈溢出.md
  - pwn/源代码编译过程.md
  - pwn/格式化字符串.md
  - pwn/堆.md
  - pwn/堆利用.md
  - pwn/Canary.md
  - pwn/Sandbox Escape.md
- 编程语言:
  - 编程语言/python.md
  - 编程语言/php.md
  - 编程语言/javascript.md
  - 编程语言/java.md
  - 编程语言/java代码审计.md
  - 编程语言/codeql.md
- 逆向:
  - reverse/start.md
  - reverse/汇编/bomb.md
  - reverse/ollydbg/ollydbg.md
- CTF:
  - ctf/start.md
  - ctf/编码、密码.md
  - ctf/杂项.md
  - ctf/php代码审计.md
  - ctf/awd.md
  - ctf/ctf资讯和靶场.md
- 资料:
  - 资料/start.md






  